#!/usr/bin/env python3
"""Codegen: Move package addresses → Python constants for SDK consumers.

Mirror of `codegen-move-types.ts` for the Python SDK. Reads
`config/networks.json` and emits
`packages/sdk-python/onemem/generated/addresses.py`, a constants module
every `onemem-sdk-python` consumer imports to resolve the deployed package
ID + registry ID for the active network at runtime.

Run: `uv run python scripts/codegen-move-python.py`

v0.1 scope: structural types (Pydantic models for MemoryNamespace,
ActionCall, etc.) are hand-written under
`packages/sdk-python/onemem/types/move_types.py` during Pillar 2 SDK
work — they don't drift because Move modules are immutable per Sui
publish semantics. v0.2+ may extend this script to fetch the on-chain
package's BCS schema and validate the hand-written types match.

Spec: docs/05-our-architecture/00-overview/TOOLING_DECISIONS.md
      "Cross-language coordination" section.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "networks.json"
OUTPUT_PATH = REPO_ROOT / "packages" / "sdk-python" / "onemem" / "generated" / "addresses.py"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text())


def deployed_networks(cfg: dict) -> list[tuple[str, dict]]:
    return [(n, b) for n, b in cfg["networks"].items() if b["package_id"]]


def render(cfg: dict) -> str:
    header = '''"""AUTOGENERATED by scripts/codegen-move-python.py — do not edit by hand.

Source of truth: config/networks.json. Rerun the codegen after every deploy.

Usage:
    from onemem.generated.addresses import addresses_for, ACTIVE_NETWORK
    import os
    addrs = addresses_for(os.environ.get("SUI_NETWORK", ACTIVE_NETWORK))
    pkg = addrs.package_id
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal

SuiNetwork = Literal["testnet", "mainnet", "devnet", "local"]


@dataclass(frozen=True, slots=True)
class OneMemAddresses:
    network: SuiNetwork
    rpc_url: str
    suiscan_base: str
    package_id: str
    original_package_id: str
    registry_id: str
    registry_admin_cap_id: str
    upgrade_cap_id: str
    deployer_address: str
    tx_digest: str
    deployed_at: str

'''
    active = f'ACTIVE_NETWORK: SuiNetwork = "{cfg["active"]}"\n\n'

    addr_entries = []
    for name, b in deployed_networks(cfg):
        entry = (
            f'    "{name}": OneMemAddresses(\n'
            f'        network="{name}",\n'
            f"        rpc_url={b['rpc_url']!r},\n"
            f"        suiscan_base={b['suiscan_base']!r},\n"
            f"        package_id={b['package_id']!r},\n"
            f"        original_package_id={(b.get('original_package_id') or b['package_id'])!r},\n"
            f"        registry_id={b['registry_id']!r},\n"
            f"        registry_admin_cap_id={b['registry_admin_cap_id']!r},\n"
            f"        upgrade_cap_id={b['upgrade_cap_id']!r},\n"
            f"        deployer_address={b['deployer_address']!r},\n"
            f"        tx_digest={b['tx_digest']!r},\n"
            f"        deployed_at={b['deployed_at']!r},\n"
            f"    ),"
        )
        addr_entries.append(entry)
    addresses_block = (
        "ADDRESSES: Mapping[SuiNetwork, OneMemAddresses] = MappingProxyType({\n"
        + ("\n".join(addr_entries) + "\n" if addr_entries else "")
        + "})\n\n"
    )

    fn = (
        "def addresses_for(network: SuiNetwork) -> OneMemAddresses:\n"
        '    """Return addresses for the given network. Raises on undeployed networks."""\n'
        "    block = ADDRESSES.get(network)\n"
        "    if block is None:\n"
        '        deployed = ", ".join(ADDRESSES.keys()) or "(none yet)"\n'
        "        raise RuntimeError(\n"
        '            f"OneMem is not deployed on \\"{network}\\" — deployed networks: {deployed}. "\n'
        '            f"Run `bash scripts/deploy-contract.sh {network}` then "\n'
        '            f"`uv run python scripts/codegen-move-python.py`."\n'
        "        )\n"
        "    return block\n"
    )

    return header + active + addresses_block + fn


def main() -> None:
    cfg = load_config()
    deployed = deployed_networks(cfg)
    if not deployed:
        print(
            "codegen-move-python: no network has a deployed package yet — emitting empty ADDRESSES.\n"
            "Run `bash scripts/deploy-contract.sh testnet` (or mainnet) first; rerun this codegen after."
        )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(cfg))
    # Ensure the generated package dir is a real Python package.
    (OUTPUT_PATH.parent / "__init__.py").write_text(
        '"""Codegen-emitted artifacts. Re-run scripts/codegen-move-python.py to refresh."""\n'
    )
    print(f"codegen-move-python: wrote {OUTPUT_PATH}")
    deployed_names = ", ".join(n for n, _ in deployed) or "(none)"
    print(f"  active network: {cfg['active']}; deployed: {deployed_names}")


if __name__ == "__main__":
    main()
