#!/usr/bin/env tsx
/**
 * Codegen: Move package addresses → TS constants for SDK consumers.
 *
 * Reads `config/networks.json` and emits
 * `packages/sdk-ts/src/generated/addresses.ts`, a constants file every
 * `@onemem/sdk-ts` consumer imports to resolve the deployed package ID +
 * registry ID for the active network at runtime.
 *
 * Run: `pnpm exec tsx scripts/codegen-move-types.ts`
 *
 * v0.1 scope: structural types (interfaces for MemoryNamespace, ActionCall,
 * etc.) are hand-written under `packages/sdk-ts/src/types/move-types.ts`
 * during Pillar 2 SDK work — they don't drift because Move modules are
 * immutable per Sui publish semantics, and any v2+ schema change requires
 * an explicit migration + new VERSION constant.
 *
 * v0.2+ enhancement: extend this script to fetch the on-chain package's
 * BCS schema via `sui client object $packageId --json` and verify the
 * hand-written types match — emit a diff + fail if drift detected.
 *
 * Spec: docs/05-our-architecture/00-overview/TOOLING_DECISIONS.md
 *       "Cross-language coordination" section.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

interface NetworkBlock {
  rpc_url: string;
  suiscan_base: string;
  package_id: string;
  original_package_id?: string;
  registry_id: string;
  registry_admin_cap_id: string;
  upgrade_cap_id: string;
  deployer_address: string;
  tx_digest: string;
  deployed_at: string;
}

interface NetworksConfig {
  active: string;
  networks: Record<string, NetworkBlock>;
}

const REPO_ROOT = join(import.meta.dirname, "..");
const CONFIG_PATH = join(REPO_ROOT, "config/networks.json");
const OUTPUT_PATH = join(REPO_ROOT, "packages/sdk-ts/src/generated/addresses.ts");

function loadConfig(): NetworksConfig {
  return JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as NetworksConfig;
}

function deployedNetworks(cfg: NetworksConfig): [string, NetworkBlock][] {
  return Object.entries(cfg.networks).filter(([, b]) => b.package_id !== "");
}

function render(cfg: NetworksConfig): string {
  const header = [
    "// AUTOGENERATED by scripts/codegen-move-types.ts — do not edit by hand.",
    "// Source of truth: config/networks.json. Rerun the codegen after every deploy.",
    "//",
    "// Usage:",
    '//   import { addressesFor, ACTIVE_NETWORK } from "@onemem/sdk-ts/generated/addresses";',
    "//   const { packageId, registryId } = addressesFor(process.env.SUI_NETWORK ?? ACTIVE_NETWORK);",
    "",
    'export type SuiNetwork = "testnet" | "mainnet" | "devnet" | "local";',
    "",
    "export interface OneMemAddresses {",
    "  readonly network: SuiNetwork;",
    "  readonly rpcUrl: string;",
    "  readonly suiscanBase: string;",
    "  readonly packageId: string;",
    "  readonly originalPackageId: string;",
    "  readonly registryId: string;",
    "  readonly registryAdminCapId: string;",
    "  readonly upgradeCapId: string;",
    "  readonly deployerAddress: string;",
    "  readonly txDigest: string;",
    "  readonly deployedAt: string;",
    "}",
    "",
    `export const ACTIVE_NETWORK: SuiNetwork = ${JSON.stringify(cfg.active)};`,
    "",
    "export const ADDRESSES: Readonly<Partial<Record<SuiNetwork, OneMemAddresses>>> = Object.freeze({",
  ].join("\n");

  const blocks = deployedNetworks(cfg).map(([name, b]) => {
    const lines = [
      `  ${name}: Object.freeze({`,
      `    network: ${JSON.stringify(name)},`,
      `    rpcUrl: ${JSON.stringify(b.rpc_url)},`,
      `    suiscanBase: ${JSON.stringify(b.suiscan_base)},`,
      `    packageId: ${JSON.stringify(b.package_id)},`,
      `    originalPackageId: ${JSON.stringify(b.original_package_id || b.package_id)},`,
      `    registryId: ${JSON.stringify(b.registry_id)},`,
      `    registryAdminCapId: ${JSON.stringify(b.registry_admin_cap_id)},`,
      `    upgradeCapId: ${JSON.stringify(b.upgrade_cap_id)},`,
      `    deployerAddress: ${JSON.stringify(b.deployer_address)},`,
      `    txDigest: ${JSON.stringify(b.tx_digest)},`,
      `    deployedAt: ${JSON.stringify(b.deployed_at)},`,
      `  } satisfies OneMemAddresses),`,
    ];
    return lines.join("\n");
  });

  const footer = [
    "});",
    "",
    "export function addressesFor(network: SuiNetwork): OneMemAddresses {",
    "  const block = ADDRESSES[network];",
    "  if (!block) {",
    '    const deployed = Object.keys(ADDRESSES).join(", ") || "(none yet)";',
    "    throw new Error(",
    '      `OneMem is not deployed on "$' + '{network}" — deployed networks: $' + "{deployed}. ` +",
    "        `Run \\`bash scripts/deploy-contract.sh $" +
      "{network}\\` then \\`pnpm exec tsx scripts/codegen-move-types.ts\\`.`,",
    "    );",
    "  }",
    "  return block;",
    "}",
    "",
  ].join("\n");

  return [header, blocks.join("\n"), footer].join("\n");
}

function main() {
  const cfg = loadConfig();
  const deployed = deployedNetworks(cfg);
  if (deployed.length === 0) {
    console.warn(
      "codegen-move-types: no network has a deployed package yet — emitting empty ADDRESSES.\n" +
        "Run `bash scripts/deploy-contract.sh testnet` (or mainnet) first; rerun this codegen after.",
    );
  }
  const output = render(cfg);
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output);
  console.log(`codegen-move-types: wrote ${OUTPUT_PATH}`);
  console.log(
    `  active network: ${cfg.active}; deployed: ${deployed.map(([n]) => n).join(", ") || "(none)"}`,
  );
}

main();
